// Glossary: generated from editeur.html on 8/12/2026
window.GLOSSARY = window.GLOSSARY || {};
Object.assign(window.GLOSSARY, {
  "Laceration": "Stackable, triggers at 20 stacks to deal 6.5% ATK as Dmg per stack and remove, Duration is infinite.",
  "Selfless": "During the Duration, enemy [Laceration] stacks can exceed the limit to 100 stacks for 7s. [Selfless] state will be removed after switching Spirit.",
  "Jade Fragment": "Stacks up to 20 times. With this Buff, the first three stages of Normal can release a total of 5 sword auras. Each aura consumes 1 stack of [Jade Fragment], inflicting Dmg and 5 stacks of Laceration.",
  "Sword Will": "A resource that represents his blade's \"willpower\" (up to 7 stacks max). Every stack automatically summons a sword that attacks the target on its own. So the more Sword Will he has, the more he's basically fighting with a whole entourage of floating blades doing the work for him.",
  "Sword Shadow": "A wave of spectral blades he releases during Skill 2, hitting everything in the area in front of him. Simple but effective, anyone standing there is getting sliced.",
  "Final Dmg Up": "A damage boost applied right at the end of the combo, multiplying your total damage instead of stacking with other bonuses.",
  "Electrified": "When Electrified enemies take damage, Electrified Transfer is triggered, causing nearby Electrified enemies to take 10% of the base damage. Electrified Transfer can only be triggered once per instance of damage. Electrified lasts 8 seconds.",
  "Thunder Form": "Aerial combat state (Fight Fly Status) with permanent Super Armor. Activated via full [Wind Thunder Power] or certain Ultimates. Continuously consumes [Wind Thunder Power]; unlocks a new set of Normal Attacks (3-stage Combo) and enhances Skill effects. Ends when [Wind Thunder Power] is depleted or upon actively performing a jump action.",
  "Wind Thunder Power": "Resource/gauge that automatically regenerates over time and via hits on target. Once full, it triggers the enhanced Skill [Thunder Strike] and causes entry into [Thunder Form]. Also continuously consumed during [Thunder Form].",
  "Thunderbolt": "Stackable buff (up to 15 stacks) gained via Normal Attacks/Skills in [Thunder Form]. Each stack increases Strike Dmg (+3-4%).",
  "Furious Thunder": "Buff gained in [Thunder Form], increasing Dmg Bonus by 20% for 10s. Removed upon exiting [Thunder Form].",
  "Blitz": "An enhanced Normal Attack combo, triggered after using a Skill or Dodge, letting him jump straight into the 4th move of his combo.",
  "Yang Thunder": "Effects applied respectively by Aerial Ultimate hits ([Yang Thunder]) and Ground Ultimate hits ([Yin Thunder]). Duration 5s each. When both are present on a target simultaneously, they are consumed together to deal additional Ultimate Dmg.",
  "Yin Thunder": "A passive-triggered bonus attack, activated after enough hits land on [Scorch] targets with her Black Sword, dealing extra damage and granting [King Yin].",
  "Thunder Wrath": "Stackable buff (up to 15 stacks) gained after unleashing an Ultimate, lasting 15s. Each stack increases Strike Dmg by 4.0%.",
  "Thunderous Surge": "Charged Normal Attack (hold Normal) that rapidly consumes [Wind Thunder Power], dealing continuous Dmg per second to a wide range of nearby targets.",
  "Primal Thunder": "Effect applied to a target by a Skill hit, lasting 10s, increasing Thunderex Spirit's Dmg to that target.",
  "Flash Strike": "Buff gained for 6s after entering the aerial state; grants Thunderex Spirit a 10.0% Dmg Bonus.",
  "Support Dmg Bonus": "Support Dmg Bonus effectiveness is influenced by the ATK of the Spirit provided, and the boost rate is affected by Willpower.",
  "Frost Blossom": "Celestimums Spirit core passive Summoned Units, Survival Time 10s. [Frost Blossom] persistently tracks targets, dealing minor Dmg, and fully blooms at the end of its lifespan, unleashing numerous petal-shaped blade Dmg to nearby targets with an added [Flash] effect. Up to 4 [Frost Blossom] can exist simultaneously.",
  "Flash": "Stacks up to 99 layers, Duration 60s. When the Duration ends or certain layers are removed by specific skills [Flash], Spirimaster gains the same number of [Light Energy].",
  "Fade": "Remove a certain number of [Flash] stacks, and adds the same number of [Light Energy] to the source targets of [Flash].",
  "Light Energy": "Stacks up to 100 stacks, Duration 60s. Each stack provides 0.1% Dmg Bonus. Can be consumed by specific skills for additional effects.",
  "Chrysanthemum of the Heavens": "with a survival time of 6s. [Celestial Chrysanthemum] swiftly spins its blade-like petals, dealing ongoing Dmg to surrounding targets.",
  "Self-Admiration": "Each stack grants Celestimums Spirit Dmg Bonus, stackable up to 100 stacks, Duration 30s.",
  "Nether Court": "An effect applied by her Skill hits that boosts her Strike Damage. Basically a passive damage amplifier tied to landing skill attacks.",
  "Celestial Chrysanthemum": "The fusion result when 3 [Frost Blossom] flowers combine into one. A bigger, merged flower that carries forward the bloom effects and [Flash] stacking, essentially her \"final form\" flower.",
  "Afterglow": "A debuff from her Heartbroken as Flowers Fall ultimate. Each stack boosts the target's Flash damage taken, similar to [Radiance] but tied to a different skill.",
  "Radiance": "A stacking resource gained upon entering [Judgment Stance], consumed by [Celestial Thousand-Light Sword] hits to summon [Sword of Judgment] strikes.",
  "Skyward Frost Blossom": "An upgraded or elevated version of a normal [Frost Blossom], usually created during her Ultimate. Works the same way but tied to bigger, ultimate-scale effects.",
  "Corrosive Shadow": "When the Spirimaster is within, gain [Support Dmg Bonus].",
  "Soul Drain Claw": "Normal Attack hit has a chance to summon [Soul Drain Claw] from the ground to attack enemies, Stealing SP and dealing Dmg.",
  "Soul Fragment": "Permanently gain 5% [Support Boost], with an additional 0.5% [Dmg↓ Rate] per stack.",
  "Time Lag": "Control effect. Reduces target's action speed by a percentage.",
  "Brain Devour": "Skill and Ultimate Dmg converts to [Illusory Blood], and when attack hits consume [Illusory Blood], restores more HP.",
  "Soul Absorption": "Attack on-hit increases [Sp Regen Efficiency] by 125%.",
  "Underworld Passage": "Each stack grants 1.5% Healing Bonus, 5% Support Dmg Bonus, up to 6 stacks, Duration 60s.",
  "Locked Souls": "Gui Mei reduces target's ATK by 0.2%, gains 12% Support Dmg Bonus, Duration 20s.",
  "Illusory Blood": "Her core resource mechanic. When she takes damage, her HP converts into this resource, which she then spends to heal herself when attacking enemies. Basically turning pain into fuel.",
  "Ever Shadow": "A stacking buff gained from her Ultimate. Each stack grants extra [Support Dmg Bonus], so the more she casts her ultimate, the bigger this bonus becomes over time.",
  "Lucid Murk": "A permanent stack she gains every time she casts her Ultimate, capping at 12. It's the resource that fuels [Ever Shadow], basically a long-term investment stat.",
  "Temporal Shift": "A debuff applied to enemies in her Stalled Pole Domain, tied to the time-warping field she creates. Locks enemies into the distorted zone effect.",
  "Ghost": "The spectral allies she summons that auto-attack enemies for her. Multiple ghosts can be active at once, and their hits trigger various bonuses.",
  "Hell's Passage": "A stack she gains from her Skill 4 Ultimate. Each stack boosts Skill and Ultimate damage for all Spirits on the team.",
  "Soul Erosion": "A stacking debuff her ghosts apply to enemies. Once enough stacks build up, they get consumed for bonus Ultimate damage.",
  "Cerebral Devour": "A possession-like effect she gains after using a Skill, lasting several seconds and enhancing her abilities during that window.",
  "Scorch": "Deal 10% ATK as Dmg per second for 3s.",
  "Burn": "His core damage-over-time debuff. Applied by pretty much everything he does, it ticks damage over time on enemies and gets amplified by several of his other effects.",
  "Phoenix Supernova": "The signature effect of his Ultimate. A burning zone that deals damage per second for several seconds, then culminates in one big explosion at the end.",
  "Flame Zone": "A lingering fire patch left behind after his Ultimate's explosion. It keeps dealing a percentage of the explosion's damage over time and reapplies [Burn] to anyone standing in it.",
  "Phoenix Power": "A stacking buff gained from certain Skill hits, boosting his Strike Damage per stack, up to a cap.",
  "Fire Phoenix Domain": "A zone effect from one of his Skills. Deals damage per second, applies [Burn], and refreshes/enhances his [Blazing Phoenix] buff while active inside it.",
  "Flaming Phoenix": "A buff he gains whenever he triggers his Ultimate, Skill, or certain passives. While active, he deals extra periodic damage to nearby enemies and boosts his own [Burn] damage output.",
  "Solar Flare Shock": "A periodic burst effect from his passive, going off automatically every several seconds to blast all nearby enemies with a chunk of damage.",
  "Purgatory Flare": "A bonus burst of damage triggered automatically after [Blazing Phoenix] hits a target a certain number of times. Think of it as a \"every few ticks, get a bonus explosion\" mechanic.",
  "Phoenix Meteor Shower": "The effect from his Falling Meteor Skill, raining fiery feathers down like meteors, hitting enemies and applying [Burn] with each strike.",
  "Weakness": "Stacks up to 18 times. Ultimate inflicts special effects on targets with [Weakness]; Core Passive's [Wraith Clone] ATK on targets with [Weakness] applies [Laceration].",
  "Wraith Mark": "Her core resource, stacking up to 6 times. Depending on which Skill she uses, it swaps her aerial or ground Normal Attacks into stronger versions like [Wraith Phantom] or [Wraith Clone Slash] for a limited time after use.",
  "Wraith Phantom": "A powerful downward kick move, consuming 1 stack of [Wraith Mark] to trigger. Gets faster with each combo release. Once [Wraith Mark] runs out, her aerial Normal Attack goes back to its original form.",
  "Wraith Clone Slash": "Consumes 1 charge of [Wraith Mark] to teleport behind the target and summon multiple clones for a rapid multi-hit sword combo. Like [Wraith Phantom], it reverts once [Wraith Mark] is depleted.",
  "Wraith Clone": "The summoned shadow duplicates from her passives, auto-attacking enemies in the background, consuming [Weakness] stacks and applying [Laceration] with their hits.",
  "Wraith Spike": "A repeating strike effect from her Skill 1 Ultimate, hitting enemies periodically within the [Wraith Spike Array] and applying [Laceration], with bonus hits triggered by consuming [Weakness].",
  "Wraith Spike Array": "The zone created by her Skill 1 Ultimate where [Wraith Spike] attacks repeatedly trigger on enemies inside it.",
  "Wraith Claw": "A follow-up strike from her Skill 4 Ultimate, triggered by Normal Attacks for a duration after casting, dealing bonus damage and applying [Laceration], with extra effects if the target has [Weakness].",
  "Thousand Tribulations": "A debuff applied by enhanced [Wraith Clone] attacks, dealing [Laceration] stacks per second over its duration.",
  "Wraith Tiger Roar": "The effect from her Fusion Skill with White Tiger, applying [Laceration] stacks to every enemy hit by each Roar Wave.",
  "Godly Halo": "A buff type that boosts a Spirit's abilities.",
  "Berserk": "Every 20 stacks increase White Tiger's Normal Attack speed and Skill casting speed by 6%, causing Normal Attack Dmg Up by 5%, stacking up to 80 layers, lasting 4s. Outside of PVP mode, every [Berserk] stack limit increased to 100. 20 stacks of Berserk reduce the damage White Tiger receives by an additional 12%.",
  "Vajra Transformation": "His Skill 1 Ultimate state, lasting 15s. Immediately hits nearby enemies, resets his Skill cooldowns on entry, and boosts [Laceration] damage during its duration.",
  "White Tiger God Transformation": "His Skill 4 Ultimate state. Completely changes his Normal and Skill attack forms, grants Strong Super Armor and Control Immunity, and resets Skill cooldowns on entry. Lasts 15s (12s in PVP).",
  "Demon Transformation": "His Skill 4 Ultimate state. Completely changes his Normal and Skill attack forms, grants Strong Super Armor and Control Immunity, and resets Skill cooldowns on entry. Lasts 15s (12s in PVP).",
  "Tiger Might": "A buff gained during [Demon Transformation]. While active, every hit he lands on enemies triggers an additional bonus hit of damage.",
  "White Tiger Meteor": "The projectile summoned by his Skill 2, raining down on enemies for bonus damage, enhanced further while in Ultimate states.",
  "Phantom Fist": "A bonus attack triggered periodically during his Skill 2's enhanced window, landing extra hits on the enemy.",
  "Wraith Clones": "Summoned shadow duplicates from his passives that auto-attack enemies, consuming [Weakness] stacks and applying [Laceration] with their hits.",
  "Crimson Moon": "Gain 1 stack for each [Moon Shadow] summoned, increasing Dmg dealt by Xie Yue.",
  "Red Moon": "Gain 1 stack for each [Moon Shadow] summoned, increasing Dmg dealt by Xie Yue.",
  "Moon Shadow": "Summoned clones vanish after completing an attack.",
  "Severe Wound": "When actively dealing Dmg to enemies with [Severe Wound], trigger [Severe Wound] Dmg, max once per second. [Severe Wound] decreases by 1 layer every 2 seconds, stackable up to 200 layers. Each layer deals 0.1% ATK as Dmg.",
  "Moonshadow Mark": "Last 90s and affect the number of summoned [Moon Shadow]. Can stack up to 3 times.",
  "Invincibility": "Become immune to Dmg for a certain duration.",
  "Moon Frenzy": "A special Normal Attack state entered at 3 stacks of [Moonshadow Mark], which stops him from releasing his Normal Execute and first Normal Attack stage, changing his combo flow.",
  "Moon Madness": "Similar to [Moon Frenzy], but triggered after 40 stacks of [Crimson Moon] (likely tied to [Red Moon]), also altering his Normal Attack combo behavior.",
  "Enchant": "Her core stacking resource, built up through illusions, dodges, and nearly every Skill. Seems to fuel her overall damage and control potential the more it stacks.",
  "Descent": "A status condition on enemies that, when present, allows several of her attacks to trigger [Stun] instead of just dealing damage.",
  "Heartbreak": "A status applied to enemies caught within her illusion zones, tied to bonus effects like increased [Severe Wound] damage while active.",
  "Stun": "A crowd control effect applied to enemies (usually those in [Descent]), locking them down for a few seconds (reduced in PVP).",
  "Drift": "A special enhanced Dodge move, replacing her normal dodge, letting her combo up to three times while dealing damage and applying [Enchant] along the way.",
  "Invisibility": "A temporary stealth state she gains during dashes, dodges, and certain Skills, letting her avoid detection while positioning for her illusions.",
  "Obsession": "A status tier on enemies (implied to be an escalated version of something like [Heartbreak]), tied to bonus effects like [Heartbreak] application or [Stun] at higher Spirit levels.",
  "Dragon's Might": "Enhanced Status gained by consuming [Rage] through Firedrake passive effect, Duration 20s.",
  "Rage": "Consume [Rage] to enter [Dragon's Might] state. In [Dragon's Might] state, consume [Rage] for Dmg Bonus.",
  "Flame Blast": "Hitting enemies in [Scorch] Status immediately deals all remaining [Scorch] Dmg and consumes the [Scorch] effect. Triggers at most once every 3s.",
  "Dragon Power": "Her empowered combat state, entered by consuming [Rage]. While active, she deals bonus damage and gains various Crit Damage bonuses depending on Spirit level.",
  "Burning Rage": "A buff gained from leftover [Rage] stacks when entering [Dragon Power], boosting her damage by 15% per stack, up to a cap. Clears when [Dragon Power] ends.",
  "Dragon Body": "A defensive state granted during several of her Skills, giving her Strong Super Armor and Control Immunity while reducing all incoming damage by 50%.",
  "Dragon Strike": "An enhanced Normal Attack her first hit transforms into after using her Ultimate while in [Dragon Power] state, dealing damage and applying [Scorch] to enemies in its path.",
  "Holy Yang": "Imperial Fall's core mechanism energy, initial cap of 20 stacks, can be gained and consumed through skill mechanics.",
  "King Yin": "Imperial Fall's core mechanism energy, initial cap of 20 stacks, can be gained and consumed through skill mechanics.",
  "Dual Blades Liberation": "Her Skill 1 Ultimate state. Unlocks charged dual blade attacks and an Execute Slash that consumes all current King Yin and Holy Yang stacks for bonus damage.",
  "Greatsword Liberation": "Her Skill 4 Ultimate state. Grants Strong Super Armor and Damage Reduction, swaps her Normal Attack to a Greatsword version, and instantly floods her with 20 stacks each of King Yin and Holy Yang.",
  "Chaos": "A stack gained during [Greatsword Liberation] every time she consumes a King Yin or Holy Yang stack. Powers up her second-stage ultimate, [Chaos Annihilation], based on how many stacks she's built up.",
  "Chaos Annihilation": "The second-stage finisher during [Greatsword Liberation], dealing bonus damage scaled by her [Chaos] stacks before ending the state.",
  "Yang Flame": "The counterpart passive trigger, activated after enough hits land on [Electrified] targets with her White Sword, dealing extra damage and granting [Holy Yang].",
  "Falling Thunder": "A bonus AoE effect triggered when inflicting [Yin Thunder] on an already [Electrified] target, dealing extra Electrified damage to nearby enemies.",
  "Flammable Conductor": "A debuff applied by an enhanced [Yin Thunder], boosting both Electrified and Scorch damage taken by the target for a short duration.",
  "Yin-Yang Disintegration": "A debuff applied after certain enhanced Skill combos, allowing all Spirits on the team to trigger Electrified damage on affected targets.",
  "Synergy Dmg": "Dmg is considered dealt by the Spirit with the highest ATK among deployed Spirits, but the Dmg source belongs to the Skill source Spirit.",
  "Frenzied Flame": "Spirit Pyrelord's specific skill can consume [Fury Fire] to apply [DEF Vulnerability] to the target, up to 30 stacks.",
  "Sandstorm": "Rock protrusion inflicts ATK Dmg and grants [Fury Fire], triggering every 30s.",
  "Holy Flame": "Each layer deals 10% ATK as [Scorch] Dmg per second, Duration 20s, base layer cap is 1.",
  "DEF Vulnerability": "The effectiveness of DEF Vulnerability is influenced by the ATK of the Spirit provided, and the amplification rate is affected by Willpower. This works the same way as Control Vulnerability in Dmg calculation.",
  "Bone Melting": "Causes Dmg to the marked HP and gains [DEF Vulnerability], Duration 60s, up to 5 stacks, repeated acquisition stacks and refreshes marked HP and Duration.",
  "Normal Combo": "A follow-up punch combo unlocked after using a Skill, Dodge, or final Normal Attack. Each hit consumes 1 stack of [Fury Fire], applies [Scorching Soul], and extends [Holy Flame] duration.",
  "Aerial Normal Combo": "The airborne version of [Normal Combo], triggered after an aerial Normal Attack lands. Consumes 3 stacks of [Fury Fire] per hit, applies 3 stacks of [Scorching Soul], and extends [Holy Flame] by more.",
  "Scorching Soul": "Similar to [Molten Bone], another stacking HP-based mark that grants [DEF Vulnerability] on damage to the marked portion, up to 20 stacks.",
  "Lava Territory": "A zone created by his Skill 4 Ultimate, trapping allies and enemies inside (with some boss exceptions), slowing enemies and dealing continuous damage.",
  "Fury Fire": "His core resource, generated through blocks and [Sandstorm], consumed by his Skills to apply Vulnerability-related marks.",
  "Unyielding Roar": "A passive counterattack triggered after a successful block followed by a Normal Attack, dealing big Synergy damage and applying [Cower].",
  "Cower": "A debuff applied by [Unyielding Roar], reducing damage taken by the Spiritmaster from affected enemies while boosting the team's Scorch damage against them.",
  "Crushing Blow": "A passive counterattack from Skill 5, triggered after a successful block, dealing massive Synergy damage and applying [Stun].",
  "Shock": "Up to 10 stacks, for 30s. Upon reaching max stacks, all [Shock] will convert to [Vibration].",
  "Vibration": "Shock transforms into Vibration after accumulating 10 stacks. During this time, Shock is consumed to deal additional damage, with each stack dealing 15% additional damage. Vibration lasts 10 seconds.",
  "Supple Rabbit Ghosts": "Summoned spectral rabbit clones that stay on the field for a duration, auto-attacking enemies continuously. Multiple ghosts can stack their damage together.",
  "Frenzy": "A buff state entered after using her Ultimate or under certain conditions, boosting things like Rabbit Ghost attack speed and damage while active.",
  "Balance Break Slash": "A powerful bonus Skill hit tied to her passive, dealing big damage and scaling further based on target type (bonus damage vs Minions/Elites at high Spirit levels).",
  "Rapid Assault": "A temporary state entered after using certain Skills, altering the fourth Normal Attack combo into a special follow-up called Soft Bone Spin, lasting 15s.",
  "Fleeting Hare": "Supple Rabbit releases different types of Skills during ATK (e.g., using Normal in Skill, using Long Press Normal in Normal, etc., Long Press Normal swiftly gains [Fleeting Hare]), if [Fleeting Hare] is not gained, gain 1 stack of [Fleeting Hare]. Stacks up to 10 layers, Duration 10s. Each layer Dmg Up 2%.",
  "Supple Rabbit Phantoms": "Supple Rabbit's summon has an initial survival time of 5s, automatically attacking the target, and adding 1 stack of [Shock] to the target each time hitting a non-Vibration target.",
  "Thunder Spread": "When taking Dmg from active skills, triggers a Thunder, dealing a total of 12% Dmg to nearby enemies. Trigger interval is 1s. During the Duration, cannot apply [Hunt Mark].",
  "Feather": "A stacking resource gained per [Light Energy] stack (in the Glacial Arrow build), converting into [Glacial Shard] stacks every 7 accumulated.",
  "Pursuit Mark": "A stacking debuff applied to enemies via [Feather] hits. Once an enemy reaches 50 stacks, the Owl unleashes a big burst hit and clears all stacks at once.",
  "Hunt Mark": "Referenced alongside [Pursuit Mark], tied to the same stacking system, some upgrades grant bonus stacks of this on the first hit from Initiative or Skill.",
  "Death Feast": "Each stack increases [Deadly Spider] self-destruct ATK Dmg, Duration 30s, stacks up to 10 stacks.",
  "Rakshasa Mark": "Duration is permanent. Adds 35% [Control Vulnerability], and provides a target with a maximum of 30 stacks of [Severe Wound].",
  "Death Mark": "[Death Mark] adds [Control Vulnerability], lasting 20s.",
  "Cobweb": "A web zone created by Skill 1, trapping enemies inside for its duration. Applies [Death Bind] continuously to trapped targets, stacking [Control Vulnerability].",
  "Imprison": "A crowd control effect applied on entry to [Cobweb], locking enemies in place for a few seconds.",
  "Death Bind": "The continuous effect applied to targets trapped inside [Cobweb], granting bonus [Control Vulnerability].",
  "Death Spider": "Summoned spider minions that descend along webs, self-destruct on contact, and deal bonus damage while applying [Death Mark] and other debuffs.",
  "Devouring Silk": "A stacking debuff applied by Skill 4, each stack adding [Control Vulnerability], up to a max of 10 stacks.",
  "Deadly Domain": "The zone effect created by Skill 4, lasting 15s, continuously firing webs at enemies inside.",
  "Eternal Rift": "A debuff applied by Skill 2, tied to triggering [Severe Wound Enhancement] stacks on hit.",
  "Severe Wound Enhancement": "A stacking buff gained whenever [Severe Wound] is applied, each stack boosting [Severe Wound] damage for a duration, up to 10 stacks.",
  "Death Spider Demon": "The summoned spider from Skill 6, connecting enemies with webs, applying Traction and dealing damage before self-destructing.",
  "Cursed Silk": "A stacking debuff applied by [Death Spider] web shots, each stack adding [Control Vulnerability], up to 3 stacks.",
  "Abyss Mark": "The most powerful mark, triggered when [Feast of Death] hits max stacks. Permanent, adds [Control Vulnerability], and massively boosts the whole team's [Severe Wound] damage bonus.",
  "Parasite": "Auto activates after 10s, dealing Dmg and applying [Imprison] effect for 3s, 1s for boss",
  "Silvan Area": "All enemies in the area take Dmg every second for 5s.",
  "Silvan Toxin": "A stacking debuff applied to hit enemies, increasing [Control Vulnerability] for a duration.",
  "Control Vulnerability": "Control Vulnerability effectiveness is influenced by the ATK of the Spirit provided, and the boost rate is affected by Willpower.",
  "Healing Sprite": "The core stacking resource. Generated whenever any Spirit on the team lands a Normal Attack, each stack providing passive HP regen per second. Consumed by Ultimates for bonus healing effectiveness.",
  "Divine Healing": "A defensive buff applied by Skill 6, reducing damage taken and refunding HP whenever the Spiritmaster takes damage, up to 3 triggers before it's removed.",
  "Bloom": "A buff gained after using certain Ultimates, restoring SP per second for a duration.",
  "Healing Chain": "An effect created by Skill 4's planted sceptre, connecting to a target and healing them periodically over its duration.",
  "Wolf's Spirit": "In [Wolf's Spirit] form, Normal Attack changes, Dmg significantly increases. Cannot gain [Wolf's Mark] during the form.",
  "Wolf's Mark": "Stackable, max 10 stacks. Unleashing the Ultimate at full stacks will activate [Wolf's Spirit] form.",
  "Seething": "If not in [Wolf's Spirit] form, Normal starts from the third stage, lasting 6s.",
  "Furious Wind": "Additional Attack, the Windbell Bird phantom swiftly passes through the current target, dealing a portion of Dmg. Applies a certain stack of [Laceration] to hit enemies. When multiple [Furious Wind] attacks are released simultaneously, the release count will be stored and released at a frequency of once every 0.5 seconds.",
  "Windburn": "Dmg is taken based on the number of [Laceration] stacks, up to 50 stacks, Duration 9s.",
  "Wind Field": "A zone effect created by certain Skills, boosting ally movement speed and enhancing follow-up Skills when passed through.",
  "Wind Fury": "A variant of [Furious Wind] triggered specifically during Skill 4's Ultimate, dealing bonus damage and applying [Laceration] stacks.",
  "Force Break": "Obtained through Passive, up to 2 layers. Consumes All layers when releasing the ultimate, each layer increases ultimate Dmg by 5%.",
  "Momentum": "His core stacking resource. Gained with each successful hit, up to 50 stacks, each providing a small Damage Bonus. Decays if he stops attacking for too long.",
  "Break·Slash": "The charged Normal Attack, a jump-and-slash-down move triggered by holding the Normal Attack button.",
  "Exude": "The follow-up Normal Attack effect triggered after a Skill or Dodge, part of the [Blitz] combo chain.",
  "Break·Vanquish": "An enhanced charged attack unlocked at 15 stacks of [Momentum], dealing double damage and granting a stack of [Force Break].",
  "Break·Destruction": "An alternate name/version of the enhanced charged attack tied to Skill 5, functioning similarly to [Break·Vanquish].",
  "Soul Freeze": "All Dmg taken increased, Duration 10s.",
  "Icering Armor": "Consumes one stack upon taking Dmg, reducing Dmg taken by 20% and applying 2 stacks of [Icebound] to the attacker, which triggers only once every 5s.",
  "Icebound": "Speed reduced by 1% for 5s, stacks up to 10 times.",
  "Permafrost Domain": "[Icebound] on all enemies in the area per second, while increasing Character movement Speed by 20%.",
  "Bone Chill": "A debuff applied when ice spikes explode, increasing [Control Vulnerability] for a duration.",
  "Frozen Expanse": "A bonus damage effect triggered while enemies are [Frozen], dealt again when they take other Ultimate damage during that window.",
  "Frozen": "A crowd control effect applied by several Skills, locking enemies in place for a short duration.",
  "Pagoda Sigil": "Duration 60s, six different effects: ·Strength: HP increase ·Speed: Movement Speed increase ·Soul: Restore SP over time ·Defense: Dmg Reduction ·Attack: ATK increase ·Boost: Support Dmg Bonus. Each layer randomly grants one of these effects, initial cap of one layer.",
  "Septa Divine Light": "A buff granted by the Ultimate, reducing all team Ultimate Soul Power costs and cooldowns for its duration. Only activates once (or twice at higher Spirit levels).",
  "Enfeeble": "Target cannot act and receives increased Dmg.",
  "Break Toughness": "When the target's toughness bar is depleted, trigger Break Toughness effect, entering Enfeeble state.",
  "Silvan Emperor": "Silvan Domain summons, up to 4 can exist simultaneously. When the Silvan Emperor Spirit unleashes its Ultimate, it sacrifices the Silvan Emperor for additional effects.",
  "Sacrificial Thorn": "A debuff applied by both Ultimates, granting bonus [Control Vulnerability] for its duration.",
  "Silvan Strangle": "A debuff from Skill 1's Ultimate, reducing the target's Max Poise repeatedly and applying short bursts of [Imprison] over its duration.",
  "Earthbind": "A stacking debuff from Skill 4's Ultimate, extending the target's [Enfeeble] duration whenever they trigger [Break Toughness], up to 5 layers.",
  "Dormancy": "A 360-second cooldown state required to restore a used-up [Silvan Emperor] Reset charge.",
  "Devouring Gold Silk": "A stacking debuff applied when sacrificing [Silvan Emperor] during the Ultimate, increasing the target's Toughness damage taken, up to 4 stacks.",
  "Silvan Domain": "The battlefield-covering zone summoned on entering the fight, continuously applying [Control Vulnerability] to all targets within.",
  "Silvan Emperor Toxin": "A stacking debuff applied for each sacrificed [Silvan Emperor], granting bonus [Control Vulnerability] to all targets in the domain.",
  "Silvan Seed": "A planted trap created by Skill 6, triggering a vine-strangling attack and gathering nearby targets when stepped on.",
  "Parasite Thorn": "A stacking debuff from Skill 5's Ultimate, converting into [Celestial Thorn] stacks when the target triggers [Enfeeble].",
  "Celestial Thorn": "The upgraded debuff converted from [Parasite Thorn], increasing the target's damage taken bonus while under [Enfeeble].",
  "Silvan Thorns": "A debuff applied by Skill 2 when the core passive is active and a [Silvan Emperor] is present, granting [Control Vulnerability].",
  "Detonation": "Only [Spider Toxin] triggers [Detonation]. Triggering [Detonation] deals additional Dmg based on ATK.",
  "Poisoned": "Take minor Dmg per second, with an initial Duration of 10s, and repeated stacking extends the Duration by 3s.",
  "Frenzied Devourer": "Increases your ATK Speed by 1% and Dmg Dealt by 0.15%. Deals Dmg to nearby enemies every second based on stack count. The ATK Speed bonus only applies to [Annihilation Gaze] and [Spider Summon]. Max 100 stacks.",
  "Poison Frenzy": "Poison Dmg to 1000% in 15 seconds, during which [Spider Summon] adds 2 stacks of [Bloodlust Toxin].",
  "Poison Blast": "[Soulless Toxin]: For 15s, increases Poison Dmg by 1000%. During this time, [Spider Summon] applies 2 stacks of [Soulless Toxin].",
  "Venom Pool": "[Venom Pool] consists of [Toxic Abyss] and [Venom Detonation]. A special gauge for the [Venom Pool] is displayed above the HP bar, with [Toxic Abyss] on the left and [Venom Detonation] on the right. All DMG stored in the [Venom Pool] is first funneled into [Toxic Abyss]. Each time the Soul-Eating Arachnid switches to the field, a portion of the DMG in [Toxic Abyss] is transferred to [Venom Detonation], where it continues to accumulate. While the Soul-Eating Arachnid is on the field, any DMG that can be stored in the [Venom Pool] will be augmented by the DMG stored in [Venom Detonation]. The bonus DMG is equal to 100% of the original DMG.",
  "Spider Toxin": "[Spider Toxin] has three types: [Marrow Erosion Toxin], [Bloodlust Toxin], and [Soulless Toxin].",
  "Settlement": "Only [Spider Toxin] triggers [Detonation]. Triggering [Detonation] deals additional Dmg based on ATK.",
  "Ravenous": "Increases your ATK Speed by 1% and Dmg Dealt by 0.15%. Deals Dmg to nearby enemies every second based on stack count. The ATK Speed bonus only applies to [Annihilation Gaze] and [Spider Summon]. Max 100 stacks.",
  "Settle": "Only [Spider Toxin] triggers [Detonation]. Triggering [Detonation] deals additional Dmg based on ATK.",
  "Poison": "Take minor Dmg per second, with an initial Duration of 10s, and repeated stacking extends the Duration by 3s.",
  "Venom Blast": "[Soulless Toxin]: For 15s, increases Poison Dmg by 1000%. During this time, [Spider Summon] applies 2 stacks of [Soulless Toxin].",
  "Venom Frenzy": "Poison Dmg to 1000% in 15 seconds, during which [Spider Summon] adds 2 stacks of [Bloodlust Toxin].",
  "Marrow Erosion Toxin": "One of the three Spider Toxin types, applied by the first-stage Normal Attack.",
  "Bloodlust Toxin": "Another Spider Toxin type, applied by the second-stage Normal Attack.",
  "Soulless Toxin": "The third Spider Toxin type, applied by the third-stage Normal Attack.",
  "Soul-Eating Barrier": "A damage zone summoned by Skill 1's Ultimate, dealing continuous damage, reducing damage taken while active, and exploding at the end.",
  "Spider Sense": "The randomized state granted by [Venom Codex], giving one of [Blazing Venom], [Venom Frenzy], or [Venom Blast] while active.",
  "Venom Codex": "A passive state that, when active, causes Ultimate/Skill damage to be added to the [Venom Pool] and randomly grants one of three enhanced toxin effects.",
  "Blazing Venom": "The three possible enhanced toxin effects randomly granted through [Spider Sense], each boosting toxin damage in different ways.",
  "Venom Detonation": "An effect that converts stored [Venom Pool] damage into a bonus payout, with its conversion rate boosted at higher Spirit levels.",
  "Venomous Reign": "The passive that increases the [Spider Toxin] stack cap to 50 and enables converting enemy Poison/Toxin into [Ravenous], also altering the Normal Attack form while active.",
  "Weave Calamity": "The buff granted to the Spiritmaster upon using the Fusion Skill, providing 10% Final Dmg Up for 180 seconds.",
  "Weave Doom": "Referenced in the upgrade tiers as another name tied to the buff granted to the Spiritmaster (likely interchangeable with or an upgraded version of [Weave Calamity]), boosting Final Dmg Up to 20% at max tier.",
  "Spider Bite": "Referenced in the upgrade tiers as the damage type tied to the Fusion Skill's effect (likely the formal name for [Arachnid Bite]'s damage instances), boosted by 50% at higher Spirit combination tiers.",
  "Arachnid Bite": "A debuff applied to enemies by the Fusion Skill, dealing repeating damage every 3 seconds over a long 180s duration.",
  "Spider Summon": "The Fusion Skill itself, where the Soul-Eating Arachnid and Death Arachnid combine into a Twin Arachnid, diving down to deal massive area damage while granting buffs/debuffs to both sides.",
  "Ascend": "Max 12 stacks, each stack grants Seraph Spirit 3.5% Dmg Bonus. At max stacks, unlock 3-stage Ultimate [Final Judgment].",
  "Execution Stance": "The transformed state entered via Skill 1's Ultimate. Grants aerial combat, enhanced Skills/Evasion, [Zeal], an enhanced Normal Attack combo, and access to [Verdict Purge] and [Light Energy] mechanics.",
  "Zeal": "A buff granted upon entering either Ultimate stance, providing Strong Super Armor and Control Immunity for its duration.",
  "Blade of Execution": "The colossal sword summoned during [Execution Stance], used for her enhanced Normal Attack combo.",
  "Verdict Purge": "A stacking resource gained upon entering [Execution Stance], consumed by enhanced Normal Attacks to summon [Pure Blade] strikes.",
  "Pure Blade": "A flame-wrapped bonus attack summoned by consuming [Verdict Purge] stacks during enhanced Normal Attacks in [Execution Stance].",
  "Final Execution": "An enhanced Charged Normal Attack, activated once [Light Energy] reaches 60 stacks, consuming all stacks for bonus area damage.",
  "Resolution": "A stack gained from releasing the Ultimate, enhancing the next [Final Execution] with bonus damage.",
  "Judgment Stance": "The transformed state entered via Skill 4's Ultimate. A deeper three-stage Ultimate progression system built around [Radiance], [Light Energy], and [Ascend].",
  "Sword of Judgment": "Summoned blades tied to [Judgment Stance], dealing damage and applying [Flash] when triggered by [Radiance] consumption.",
  "Celestial Thousand-Light Sword": "A brief enhanced state entered during [Judgment Stance]'s Normal Attack combo, unlocked by holding [Radiance] stacks, granting swift aerial sword wave attacks.",
  "Judgment Descent": "The first-stage Ultimate of [Judgment Stance].",
  "Light's End": "The second-stage Ultimate, unlocked after entering [Judgment Stance], converting removed [Flash] stacks into self [Light Energy].",
  "Final Judgment": "The third-stage Ultimate, unlocked at max [Ascend] stacks, consuming all [Light Energy] for a massive finishing strike.",
  "Fervent Zeal": "A buff granted by Skill 6, causing Normal Attacks to deal bonus damage based on the target's [Flash] stack count.",
  "Fervent Heart": "A stacking buff gained from Normal Attack hits during [Fervent Zeal], boosting Seraph Ultimate Dmg per stack.",
  "Holy Fire": "A stacking debuff applied during [Fervent Zeal], detonating for bonus damage once it reaches max stacks.",
  "Domain of Execution": "A lingering zone deployed after the Ultimate ends (tied to [Execution Stance]), boosting Seraph Ultimate damage to targets inside and dealing bonus [Umbral Light] damage when [Flash] is removed.",
  "Umbral Light": "The passive damage effect triggered within [Domain of Execution] whenever [Flash] is removed from a target.",
  "Domain of Judgment": "A lingering zone deployed after the Ultimate ends (tied to [Judgment Stance]), boosting Seraph Ultimate damage to targets inside and dealing bonus [Refracted Light] damage when [Flash] is applied.",
  "Refracted Light": "The passive damage effect triggered within [Domain of Judgment] whenever [Flash] is inflicted on a target.",
  "Bone Erosion": "Each stack marks the target with 15% Max HP (marks 100% Max HP for Normal or Elite Monsters), Duration 60s, up to 3 stacks. Dmg to marked HP gains 40% [DEF Vulnerability] effect.",
  "Bone Armor": "Grants a Shield Value based on Bonedragon's max HP, granting all Spirits a Medium Super Armor effect for 30s while the shield is active.",
  "Space Gate": "Using Jump near [Space Gate] will transport you to another [Space Gate] in the same group, then the group will close but remain on the field. [Space Gate] lasts up to 60s after creation, with a maximum of 1 group on the field.",
  "Dragonbone Fragment": "Upon acquiring [Dragonbone Sturdy Armor], consume all [Dragonbone Fragments] and additionally gain Shield Value equal to the consumed quantity of [Dragonbone Fragments] multiplied by a certain rate of maximum HP.",
  "Dragonbone Sturdy Armor": "Grants a Shield Value equal to a certain percentage of Bonedragon's maximum HP, providing all Spirits with Strong Super Armor while the shield is active, with no Duration limit, and still considered as [Bone Armor].",
  "Dragon Transformation": "A buff gained after casting Skill 1's Ultimate. Consumes [Bone Armor] Shield Value periodically to summon bonus Bonedragon attacks, cycling through three different attack phases.",
  "Void Phantom Armor": "Another enhanced version of [Bone Armor], granting Medium Super Armor with no duration limit. When shattered, absorbs overflow damage and grants [Void].",
  "Void": "A buff granted when [Void Phantom Armor] shatters, providing a large Final Dmg Reduction bonus to all Spirits for a short duration.",
  "Delicate Aroma": "Delicate Aroma Spirit summon, only 1 can exist at a time. Delicate Aroma Spirit can adjust its position.",
  "Lingering Fragrance": "Gain Super Armor, and continuously restore HP.",
  "Refreshing Fragrance": "Dispel negative status upon acquisition, and continuously restore HP.",
  "Trace of Fragrance": "SP Restore upon acquisition, increases [Support Dmg Bonus] by 1.5% per stack. [[Fragrance Trace]] layers cannot be gained while [[Fragrance Tracking]] is active.",
  "Enhance Initiative": "The Character recalls [Delicate Aroma], and [Delicate Aroma] appears beside the character, dealing Dmg to nearby enemies and knocking back surrounding targets.",
  "Soothing Aroma": "A buff applied to all allies via Skill 4's Ultimate, providing healing per second and dispelling negative status on receipt.",
  "Fragrance Tracking": "The converted effect granted when [Fragrance Trace] stacks are consumed near [Delicate Aroma].",
  "Floral Resonance": "A stacking buff gained when consuming more than 10 layers of [Fragrance Trace] at once, increasing [Support Dmg Bonus] per layer.",
  "Delicate Melody": "A buff granted when consuming more than 10 layers of [Fragrance Trace] at once (at high Spirit level), providing a large [Support Dmg Bonus].",
  "Aroma": "A stacking resource (alternate passive version of Fragrance Trace) gained while standing in the Fragrance Domain, each stack boosting [Support Dmg Bonus] and restoring Soul Power.",
  "Heavenly Melody": "A buff granted when [Aroma] reaches full stacks, providing bonus [Support Dmg Bonus],",
  "Light Song": "A buff gained after unleashing Skill 1's Ultimate at high Spirit level, granting Control Immunity.",
  "Graceful Dance": "A buff gained alongside [Light Song], increasing [Support Dmg Bonus] for its duration.",
  "Floral Veil": "A buff gained after unleashing Skill 4's Ultimate at high Spirit level, granting Control Immunity.",
  "Jade Melody": "A buff gained alongside [Floral Veil], increasing [Support Dmg Bonus] for its duration.",
  "Purification": "A buff gained after releasing a Skill (Skill 6 passive), granting Control Immunity.",
  "Soul Wander": "A buff gained after using a Skill (Skill 6, higher Spirit level), granting Strong Super Armor.",
  "Fragrance Trace": "SP Restore upon acquisition, increases [Support Dmg Bonus] by 1.5% per stack. [[Fragrance Trace]] layers cannot be gained while [[Fragrance Tracking]] is active.",
  "Enhanced Initiative": "An upgraded version of the Initiative skill, unlocked by either passive, allowing instant activation even while attacked or controlled.",
  "Ice Arrow": "Max 6 stacks. Upon reaching max stacks of [Ice Arrow], activates Enhanced Normal Attack and enters [State of Mind].",
  "Glacial Shard": "Max 20 stacks. Possessing 6 stacks of [Glacial Shard] activates Enhanced Normal Attack [Glacial Arrow].",
  "Stride": "A quick dash mechanic triggered by moving the joystick during Normal Attack combos, letting him fire arrows while repositioning.",
  "Glacial Arrow": "The alternate passive, granting [Glacial Shard] stacks instead of Ice Arrow, all consumed at once for a scaling burst attack.",
  "Starry Plume": "A buff applied by Ultimate hits, boosting Lightfeather Bow's damage for its duration and dealing bonus damage on expiration, scaled by hits from [Formless Arrow]/[Glacial Arrow] during that window.",
  "Formless Arrow": "One of two Core Passives. Grants [State of Mind] upon using the enhanced Charged Normal Attack, unlocking a powerful line-piercing shot that consumes [Ice Arrow] and converts [Flash] into [Light Energy].",
  "State of Mind": "An aiming-lock stance entered via [Formless Arrow]'s Core Passive, disabling movement but granting an enhanced special dodge and access to the Formless Arrow attack.",
  "Star Mark": "A stacking debuff applied by certain Skills, increasing Strike Damage from [Formless Arrow] or [Glacial Arrow] hits per stack.",
  "Polar Glimmer": "A debuff applied by [Glacial Arrow] hits, increasing Flash damage taken by the target, with bonus triggered damage when Flash is applied/removed by other Spirits while active.",
  "Fiery Shadow Scorch": "A debuff applied by Skill 1's Ultimate, granting bonus [Control Vulnerability] for its duration.",
  "Fire": "A buff applied on Ultimate hit, reducing the interval between [Scorch] periodic damage ticks, making Scorch tick faster.",
  "Fire Thorns": "Fiery Shadow Spirit Core Passive. After the target takes [Scorch] Dmg, consume [Fire Thorns] stacks to deal Dmg and apply [Control Vulnerability].",
  "Fiery Scorch": "A debuff applied by Skill 4's Ultimate, increasing the target's Control Vulnerability for its duration.",
  "Flame Molding": "A buff applied on Ultimate hit at higher Spirit levels (Skill 4), duration and effect not fully detailed beyond its application.",
  "Weaving Dance": "A buff gained from Skill 6, enabling her Fiery Shadow companion to auto-attack when switching to another Spirit and landing a Normal Attack.",
  "Fire Thorns Vulnerability": "A stacking debuff applied when [Fire Thorns] is consumed (Skill 5 variant), each stack granting [Control Vulnerability], up to 12 stacks.",
  "Fire Thorns Bloom": "An upgraded state entered when [Fire Thorns Vulnerability] reaches full stacks, granting a bigger flat [Control Vulnerability] bonus for its duration, during which no new Fire Thorns can be added.",
  "Fiery Shadow Strike": "The bonus attack triggered by [Weaving Dance], dealing damage and applying [Scorch], with bonus [Fire Thorns] stacks if the Core Passive is active.",
  "Fiery Shadow Blitz": "The bonus attack triggered by [Weaving Dance], dealing damage and applying [Scorch], with bonus [Fire Thorns] stacks if the Core Passive is active.",
  "Snake Emperor Venom": "Immediately Immobile for 1s upon gaining effect, and gain 10% Control Vulnerability effect for 12s. [Snake Venom] cannot be acquired. Triggers at most once every 30s.",
  "Emerald Venom": "The upgraded effect [Snake Venom] converts into (Skill 3 variant), granting bonus [Control Vulnerability].",
  "Toxic": "Lasts 12s, inflicts minor Dmg per second, stacks up to 5 times. Each stack adds 5% Control Vulnerability",
  "Toxic Domain": "The zone effect created by Skill 1's Ultimate, generating Poison Orbs periodically that explode and convert [Poison] stacks into [Toxic].",
  "Poison Pool": "The zone effect created by Skill 4's Ultimate, spraying venom columns at random targets, applying [Poison] and [Immobility], and granting [Control Vulnerability] to everyone inside when it ends.",
  "Snake Venom": "A stacking resource gained equal to [Poison] applied, converting into an upgraded venom effect at 10 stacks.",
  "Root": "A debuff applied by [Time Freeze] at higher Spirit levels, granting the target additional [Control Vulnerability].",
  "Phosphorescent Poison": "A debuff tied to Skill 3, reducing healing effectiveness on the target and enhancing [Control Vulnerability].",
  "Serpent Poison": "Referenced in Skill 5's upgrades, tied to duration extensions, likely linked to the base [Poison] or [Snake Venom] mechanic.",
  "Immobility": "The core crowd control effect, locking enemies in place. Applied by nearly every Skill and Ultimate.",
  "Universal Solution": "Unlock Passive to obtain, max 9 layers. Every 3 layers of [Universal Solution] reduce one charge level of [Temporal Restriction]. Consumes All [Universal Solution] layers upon releasing [Temporal Restriction].",
  "Temporal Restriction": "The core charged ultimate effect, unlocked by fully charging via [Universal Solution] stacks. Reduces all enemies' Pose and movement Speed by 50% for its duration.",
  "Lock": "A debuff applied by Skill 1's Ultimate, tied to the [Control Vulnerability] effect granted to enemies trapped in the Broken Lock Space.",
  "Flying Lock Space": "The zone effect created by Skill 2, released when the Universe Lock hits a target or lands. Deals repeated damage every 0.2 seconds to all enemies within range over its duration, while also applying stacks of [Control Vulnerability].",
  "Showtime": "Enhanced Normal effect. If in Fight, gain 5% Dmg reduction and 5% [Support Dmg Bonus].",
  "Soul Power Storage": "[Soul Power Storage] will replenish Soul Power to full when not at maximum, up to 1300 stacks.",
  "Extremity Sausage": "When possessing [Extremity Sausage], automatically consumes [Extremity Sausage] stacks to continuously replenish Soul Power. Each stack restores 100 Soul Power, up to 8 stacks. If the required Soul Power replenishment is less than 100, consumes 1 stack of [Extremity Sausage] to gain 100 Soul Power. Remaining Soul Power will be replenished again when Soul Power is not full.",
  "Sausage": "Gain 3 stacks upon entering a Fight, removed upon exiting, with a maximum of 3 stacks. When Oscar uses an Ultimate, it consumes [Sausage] stacks for a special effect. [Sausage] restores 3 stacks every 360s.",
  "Beyond Limits": "A stacking buff gained after using the Ultimate (with Sausage present), boosting Ultimate Damage per stack, further increased by Soul Power consumption during its duration.",
  "Performance Moment": "An enhanced follow-up Normal Attack, triggered within a few seconds after using Skill 2.",
  "Hot Pursuit": "A debuff applied by Skill 6 hits, increasing Ultimate damage taken by the target from any Spirit for its duration.",
  "Roasted Sausage": "A stacking buff gained from consuming [Sausage] or when Soul Power is full, boosting [Support Dmg Bonus] per stack and granting Strong Super Armor to the whole team at 3+ stacks.",
  "Fierce Wind": "During the Buff Duration, when Gale Wolf deals [Severe Wound] Dmg, it inflicts an additional Dmg instance.",
  "Raging Wind": "During the Buff Duration, when Gale Wolf deals [Severe Wound] Dmg, it inflicts an additional Dmg instance.",
  "Gale": "Increase Gale Wolf's Dmg to Severe Wound targets based on stack count, up to 7 stacks. Dmg Up increases non-linearly: 5%, 15%, 25%, 35%, 45%, 55%, 155% for stacks 1 to 7.",
  "Feral Wolf Rampage": "Increase [Wind Fury] and summoned Wind Demon Wolf Dmg based on stack count, up to 7 stacks. Dmg Up increases non-linearly: 8%, 20%, 32%, 45%, 57%, 70%, 300% for stacks 1 to 7.",
  "Demon Wolf Frenzy": "Increase [Wind Fury] and summoned Wind Demon Wolf Dmg based on stack count, up to 7 stacks. Dmg Up increases non-linearly: 8%, 20%, 32%, 45%, 57%, 70%, 300% for stacks 1 to 7.",
  "Gale Wolf's Thirty-Six Slashes": "An enhanced Normal Attack combo that replaces standard Normal Attacks after using Skill 1's Ultimate, dealing bonus damage against [Severe Wound] targets.",
  "Demon Wolf Hunt": "A buff gained after using Skill 4's Ultimate. While active, each [Severe Wound] application summons a Demon Wolf to attack a locked target independently.",
  "Severe Wound Amplified": "A stacking debuff applied by Demon Wolf's attacks, increasing [Severe Wound] damage per stack.",
  "Gale Flurry": "An enhanced version of the Initiative Skill, unlocked on entering the fight. Grants [Gale] stacks and reduces cooldowns on key Skills.",
  "Tornado Blade": "A passive effect triggered when Gale Wolf is off-field, replacing his Initiative Skill with [Gale Blade] after enough [Severe Wound] instances land.",
  "Gale Blade": "The replacement Initiative Skill triggered by [Tornado Blade]'s passive, releasing multiple wind blades at the target.",
  "Gale Break Blade": "The replacement Initiative Skill triggered by [Tornado Blade]'s passive, releasing multiple wind blades at the target.",
  "Whirling Wind Blades": "Summoned blade projectiles from Skill 6 (Wind Blade Formation). After being hurled at the target, they continue spinning and slicing on impact, dealing repeated damage and adding a stack of [Severe Wound] with each hit, up to 10 stacks.",
  "Demon Wolf Storm": "His Skill 1 Ultimate. Summons Gale Wolf, transforming into two wolf-headed whirlwinds that spiral and collide with the ground for a wide-area explosion, applying 3 stacks of [Severe Wound] on hit. At higher Spirit levels, using this Ultimate unlocks the enhanced Normal Attack combo [Gale Wolf's Thirty-Six Slashes].",
  "Normal Pill": "Picking up different Quality [Normal Pill] grants varying Healing effects and Dmg Up stacks: Blue Pill: minor Healing effect and 1 Dmg Up stack. Purple Pill: moderate Healing effect and 2 Dmg Up stacks. Orange Pill: major Healing effect and 3 Dmg Up stacks. Dmg Up stacks from [Normal Pill] max at 15 stacks, decreasing by 1 stack every 5s.",
  "Great Pill": "Picking up [Great Pill] grants moderate Healing, special Dmg Up, and Restore 100 Soul Power. Special Dmg Up can coexist with [Normal Pill] Dmg Up effect for 20s.",
  "Nine-Turn Revival Pill": "When the player receives lethal Dmg, gain Immunity to that Dmg and additionally Restore 52% of Zenith Cauldron's max HP, then remove [Revival Pill] status, unable to gain [Revival Pill] effect again for 5 minutes.",
  "Pill Chain": "A stacking buff gained from picking up pills, increasing [Support Dmg Bonus] per stack, decaying 1 stack every 5 seconds, up to 15 stacks.",
  "Normal Elixir": "Randomly generated pills from various Skills, providing standard healing when picked up.",
  "Golden Pill": "A buff granted by the Great Golden Pill, coexisting with [Pill Chain], each stack providing bonus [Support Dmg Bonus] for its duration.",
  "Great Golden Elixir": "A guaranteed pill drop from the younger sister's Skill 2, providing enhanced healing effects.",
  "Normal Pills": "Picking up different Quality [Normal Pill] grants varying Healing effects and Dmg Up stacks: Blue Pill: minor Healing effect and 1 Dmg Up stack. Purple Pill: moderate Healing effect and 2 Dmg Up stacks. Orange Pill: major Healing effect and 3 Dmg Up stacks. Dmg Up stacks from [Normal Pill] max at 15 stacks, decreasing by 1 stack every 5s.",
  "Great Elixir": "Referenced in the upgrade tiers of Skill 6 (Completed Sky Mending), tied to a stackable pill effect whose maximum stack count and duration can be increased at higher Spirit levels. The document doesn't give it a separate base description beyond this upgrade reference, it appears to function similarly to [Great Pill]/[Great Golden Elixir] as a higher-tier pill type.",
  "Elite": "A general enemy tier, one step above regular Minions in difficulty. Elite enemies typically have more HP, hit harder, and may have special abilities or resistances that basic enemies don't.",
  "Boss": "The highest enemy tier, usually a major encounter (like a stage boss or raid boss) with significantly more HP, unique mechanics, and often immune to instant-kill or Execute effects that work on weaker enemies.",
  "Non-Boss": "Any enemy that isn't classified as a Boss, this covers both regular Minions and Elite enemies.",
  "Minion": "The lowest/basic enemy tier, regular enemies without the bonus HP, resistances, or special mechanics of Elite or Boss enemies.",
  "Spirit Swallow": "Consuming Swift's passive, each stack summons a spirit swallow to Dive at the current target, dealing Dmg and applying 1 stack of [Laceration] effect, holds up to 12 stacks.",
  "Swallow Chirping": "All Spirits' movement speed increases by 1%, [Laceration] Dmg Up by 6%.",
  "Trimmed Feather": "When receiving [Spirit Swallow] Dmg, extra Dmg is taken based on current [Laceration] stacks, up to 50 stacks [Laceration].",
  "Swift Clone": "Summoned bird clones that remain on the field, automatically attacking enemies for a set number of hits before disappearing.",
  "Swallow Clone": "Summoned bird clones that remain on the field, automatically attacking enemies for a set number of hits before disappearing.",
  "Haotian Unmatched": "Haotian Hammer enhancement effect, Duration 15s, activates every 360s.",
  "Aftershock": "After absorbing the core passive Halo, trigger [Vibration] under specific conditions, consuming [Shock], causing an [Aftershock] that deals additional Dmg to nearby enemies.",
  "Cyclone Hammer": "The transformed combat state entered via the Ultimate, changing Normal and Skill attack forms into a faster combo chain for its duration.",
  "Hammer Frenzy": "The enhanced Normal Attack combo used while in [Cyclone Hammer] form.",
  "Sumeru Haotian": "With core passive [Earth Shake Fury], gain [Sumeru Haotian], during which [Earth Shake·Great Sumeru Hammer] Dmg Up. [Sumeru Haotian] can be gained once every 360s.",
  "Sky Shatter": "A stacking resource (Core Passive: Sky Shatter Pressure), gained from applying Shock to non-Vibration targets or triggering Vibration. At 6 stacks, unlocks an enhanced airborne Normal Attack finisher.",
  "Haotian Suppression": "The enhanced airborne Normal Attack unlocked by [Sky Shatter] stacks, consuming them for bonus passive damage.",
  "Extreme·Great Sumeru Hammer": "A rare, powerful finisher unlocked after chaining multiple [Haotian Suppression] hits, dealing massive passive damage. Usable once every 360 seconds.",
  "Sky Shatter·Great Sumeru Hammer": "A follow-up finisher unlocked after using [Extreme·Great Sumeru Hammer], replacing the next aerial Normal/Combo without consuming Sky Shatter stacks.",
  "Thunderbolt Sky Shatter": "A buff gained after using Skill 1's Ultimate, boosting passive damage for its duration.",
  "Sky Shatter·Break": "A buff gained after using Skill 2, boosting Ultimate Damage for its duration.",
  "Sky Shatter·Pierce": "An alternate buff gained after using Skill 2, boosting passive damage instead of Ultimate damage.",
  "Haotian Will": "A buff gained from Skill 6, causing periodic Haotian Hammer strikes to fall from the sky over its duration.",
  "Earthquake": "The alternate stacking resource, gained from Vibration damage triggers. At 10 stacks, unlocks an enhanced airborne Normal Attack finisher.",
  "Mighty Enemy Breaker": "A buff gained from executing an aerial Normal Attack (Earth Shake Fury passive), recording all Spirit-induced Vibration damage for a window, later dealt as bonus damage when triggering the finisher.",
  "Earth Shake: Great Sumeru Hammer": "The enhanced airborne Normal Attack finisher unlocked by [Earthquake] stacks, consuming them all for bonus passive damage.",
  "Sky Shatter Pressure": "This is actually the name of one of the two Core Passives (Skill 3), not just a standalone effect.",
  "Haotian Might": "This refers to the Innate Skill / Initiative Skill.",
  "Earth Shake": "This is the shorthand/alternate name used in the upgrade tiers for the [Earthquake] stacking resource under the Earth Shake Fury passive (Skill 5). Each stack of [Earth Shake] boosts all Spirits' [Vibration] damage, and it's fully consumed by [Earth Shake: Great Sumeru Hammer] for a big finishing hit.",
  "Earth Shake·Great Sumeru Hammer": "The finisher move unlocked under the Earth Shake Fury Core Passive (Skill 5), triggered when [Earthquake]/[Earth Shake] stacks reach 10 or more. It replaces the airborne Normal Attack, consuming all accumulated Earthquake stacks at once to deal a massive burst of passive damage, scaling even higher if extra Earthquake stacks were banked beyond the 10-stack threshold, and further boosted while under [Sumeru Haotian] or against [Vibration] targets.",
  "Ennea Pagoda Sigil": "Duration 120s, with six different effects: ·Strength: Increase HP ·Speed: Increase movement Speed ·Soul: Continuously Restore SP ·Defense: Dmg Reduction ·Attack: Increase ATK ·Boost: Support Dmg Bonus. Each layer randomly grants one of these six effects. The sigil can be acquired again to upgrade to Tier 2, further enhancing the effect.",
  "All-Purpose Status": "Acquired through Halo 3 effect. Upgrades all current sigils to Tier 2 upon acquisition. Upon exiting this Status, remove all [Ennea Pagoda Sigils].",
  "Omniscient Status": "Obtained through the Halo 5 effect. When in [Omniscient Status], all acquired [Ennea Pagoda Sigil] automatically Upgrade to Lv.2.",
  "Omniscient State": "Obtained through the Halo 5 effect. When in [Omniscient Status], all acquired [Ennea Pagoda Sigil] automatically Upgrade to Lv.2.",
  "Control Immunity": "A general defensive buff that makes the character immune to crowd control effects like Stun, Imprison, Freeze, or Knockback for its duration.",
  "Strong Super Armor": "A general defensive buff granting a high tier of poise/hyper armor, preventing the character from being interrupted or staggered by enemy attacks while active, often also reducing incoming damage. It's a stronger version of standard Super Armor, harder for enemies to break through."
});
